= Journey in the heart of Graphgen

== Graphgen internals, generation and import

A journey into the heart of Graphgen, the graph generation engine for Neo4j 


To my surprise, sharing a simple command line tool screencast capable of generating a graph based on a user yaml schema file became to be a powerful online web application for generating graphs and importing them in a Neo4j graph database, this application is called Graphgen.

More features were implemented by the time, visualization of the graph, multiple format exports, integration with the neo4j console web application, and last but not least custom node models.

While the web application is a good deal for simple graphs, when you want to use it in consultancy for generating test graphs permitting a realistic load impact test you need more than the current limit of 1000 nodes restricted by the web application (mostly for the vizualisation). This is why using it as command line tool with Neogen is, for enterprise needs, the way to go.

Most of the users using Graphgen are just playing with it, people using the command line tool or the most curious of you may want to understand how everything works and why a big refactoring of the library is currently in process.

How it works internally ? This part will provide a global overview of how everything is handled internally, starting from the schema you until the import into the database.

Schema Parsing  On the graphgen webapp, you can only define your schema in a Cypher like DSL, in the command line tool you can use also yaml file schema definitions and easily create your own parser for your own file format.

The cypher parser is responsible for translating your patttern into a map representing your schema, in fact it will transform the cypher into the yaml format used in the cli tool, have keys for the defined nodes, relationships, properties assigned to relationships and nodes, amount of nodes and relationships cardinalities you desire.

Building an internal GraphSchema This schema is then handled by a GraphSchemaBuilder that will create a Schema object used internally, having nodes and relationships definitions and (for the upcoming version of graphgen) will declare properties on nodes as indexed or unique, useful for generating for you the queries needed in order to update your neo4j schema constraints if you import your graph.

Applying models The GraphSchema will then be passed to the Model Processor. This processor will check for each node definition if you have used a model (like Person, User) and assign the model properties on it without replacing the user defined properties. 

This is currently slightly hidden in Graphgen because of the refactoring and the ability in the future for the user to define their own models via the web app, but you can now try to type in Graphgen 

(person:#Person:#User *30)

and you’ll get 30 nodes with Person and User labels containing the following properties : _id, first_name, last_name, date_of_birth, email, password, …




Let’s build the graph ! The GraphProcessor. Once the schema build completed, it is time to generate our graph. 

This processor will start to look at the nodes definition, generating the amount of desired nodes, applying the fake data on the properties and grouping them by identifier in a map. An internal id is applied on the nodes and used as reference for the relationships between them.

The relationships will then be processed, based on the start and end node id references, and the cardinality. 4 types of cardinalities may exist : 1..1, 1..n, n..n, n..1 , by default the n..n cardinality has a max percentage. 

Each cardinality has its own handling method, which eases testing and the ability to extend the available cardinalities.

The ability to define your own percentage is part of the refactoring and tested, it will be shipped with the next version of graphgen.

The processor will return you a big array containing nodes and relationships.

Converters 


There are multiple converters available for this array.

On graphgen we use a GraphJson converter for the visualization, that will format each node and relationship to be in a displayable format for AlchemyJS and also will assign colors to node types.

The StandardCypherConverter will create for each node and relationship a Cypher statement, this converter is used when you ask for the Cypher export format and download this export as a file. You can use the content of this file to populate your own Neo4j database with the neo4j-shell.

The CypherStatementsConverter is used when you want to populate your neo4j database directly from Graphgen. It uses an optimized import query to speed up the import and importing a graph of max 1000 nodes is almost done immediately.